{{ if .Values.nfs.mountOptions -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ template "nfs-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nfs-provisioner.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storageClass.accessModes }}
  volumeMode: Filesystem
  storageClassName: ""
  selector:
    matchLabels:
      nfs-provisioner: {{ template "nfs-provisioner.fullname" . }}
  resources:
    requests:
      storage: 10Mi
{{ end -}}
