{{- if .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "nfs-provisioner.labels" . | nindent 4 }}
  name: leader-locking-{{ template "nfs-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
{{- end }}
