apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-provisioner-root
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - soft
    - timeo=30
    - retrans=3
  nfs:
    # replace with your NFS server and path
    server: 10.3.243.101
    path: /ifs/kubernetes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-provisioner-root
  # replace with namespace where provisioner is deployed
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  volumeName: nfs-provisioner-root
  resources:
    requests:
      storage: 1Mi
